from __future__ import annotations

import time
from contextlib import contextmanager
from threading import Lock

from fastapi import FastAPI
from prometheus_client import Counter, Gauge, Histogram, start_http_server
from prometheus_fastapi_instrumentator import Instrumentator

_worker_server_lock = Lock()
_worker_servers_started: set[int] = set()

upload_requests_total = Counter(
    "rag_upload_requests_total",
    "Total upload requests accepted by the API.",
)
upload_files_total = Counter(
    "rag_upload_files_total",
    "Total files accepted for ingestion.",
    labelnames=("extension",),
)
upload_file_bytes_total = Counter(
    "rag_upload_file_bytes_total",
    "Total bytes ingested by file extension.",
    labelnames=("extension",),
)

pipeline_documents_total = Counter(
    "rag_pipeline_documents_total",
    "Documents processed by pipeline worker and final status.",
    labelnames=("worker", "status", "document_type"),
)
pipeline_failures_total = Counter(
    "rag_pipeline_failures_total",
    "Pipeline failures by stage.",
    labelnames=("stage",),
)
pipeline_stage_duration_seconds = Histogram(
    "rag_pipeline_stage_duration_seconds",
    "Execution time for pipeline stages.",
    labelnames=("worker", "stage", "document_type"),
    buckets=(0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 20, 40, 80, 160),
)
chunks_generated_total = Counter(
    "rag_chunks_generated_total",
    "Chunks generated by strategy.",
    labelnames=("strategy", "document_type"),
)
chunks_per_document = Histogram(
    "rag_chunks_per_document",
    "Number of chunks generated per document.",
    labelnames=("strategy", "document_type"),
    buckets=(1, 5, 10, 20, 40, 80, 120, 200, 400),
)
embedding_batches_total = Counter(
    "rag_embedding_batches_total",
    "Embedding batches processed by status.",
    labelnames=("status",),
)
embeddings_generated_total = Counter(
    "rag_embeddings_generated_total",
    "Total chunk embeddings generated.",
)
embeddings_per_batch = Histogram(
    "rag_embeddings_per_batch",
    "Chunks embedded per worker batch.",
    buckets=(1, 5, 10, 20, 40, 80, 120, 200, 400),
)

queries_total = Counter(
    "rag_queries_total",
    "Queries processed by final status.",
    labelnames=("status",),
)
active_queries = Gauge(
    "rag_active_queries",
    "Queries currently in progress.",
)
query_duration_seconds = Histogram(
    "rag_query_duration_seconds",
    "End-to-end query latency.",
    buckets=(0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 20, 40, 80, 160),
)
query_stage_duration_seconds = Histogram(
    "rag_query_stage_duration_seconds",
    "Latency of each query processing stage.",
    labelnames=("stage",),
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 20, 40, 80, 160),
)
query_results_returned = Histogram(
    "rag_query_results_returned",
    "Retrieved documents returned to the reranker.",
    buckets=(0, 1, 2, 3, 5, 8, 12, 20, 30),
)
query_prompt_chars = Histogram(
    "rag_query_prompt_chars",
    "Prompt size in characters sent to the LLM.",
    buckets=(128, 256, 512, 1024, 2048, 4096, 8192, 16384),
)
query_answer_chars = Histogram(
    "rag_query_answer_chars",
    "Answer size in characters returned by the LLM.",
    buckets=(64, 128, 256, 512, 1024, 2048, 4096, 8192),
)


def setup_metrics(app: FastAPI) -> None:
    Instrumentator(
        should_group_status_codes=False,
        should_ignore_untemplated=True,
        excluded_handlers=["/metrics"],
    ).instrument(app).expose(app, endpoint="/metrics", include_in_schema=False)


def start_worker_metrics_server(port: int) -> None:
    with _worker_server_lock:
        if port in _worker_servers_started:
            return
        start_http_server(port)
        _worker_servers_started.add(port)


def record_upload(extension: str, size_bytes: int) -> None:
    upload_requests_total.inc()
    upload_files_total.labels(extension=extension).inc()
    upload_file_bytes_total.labels(extension=extension).inc(size_bytes)


def record_pipeline_document(worker: str, status: str, document_type: str) -> None:
    pipeline_documents_total.labels(
        worker=worker,
        status=status,
        document_type=document_type,
    ).inc()


def record_pipeline_failure(stage: str) -> None:
    pipeline_failures_total.labels(stage=stage).inc()


def record_chunks_generated(strategy: str, document_type: str, chunk_count: int) -> None:
    chunks_generated_total.labels(strategy=strategy, document_type=document_type).inc(chunk_count)
    chunks_per_document.labels(strategy=strategy, document_type=document_type).observe(chunk_count)


def record_embedding_batch(status: str, chunk_count: int) -> None:
    embedding_batches_total.labels(status=status).inc()
    embeddings_per_batch.observe(chunk_count)
    if status == "success":
        embeddings_generated_total.inc(chunk_count)


def record_query_result_count(count: int) -> None:
    query_results_returned.observe(count)


def record_prompt_size(prompt: str) -> None:
    query_prompt_chars.observe(len(prompt))


def record_answer_size(answer: str) -> None:
    query_answer_chars.observe(len(answer))


@contextmanager
def track_pipeline_stage(worker: str, stage: str, document_type: str):
    start = time.perf_counter()
    try:
        yield
    finally:
        pipeline_stage_duration_seconds.labels(
            worker=worker,
            stage=stage,
            document_type=document_type,
        ).observe(time.perf_counter() - start)


@contextmanager
def track_query_stage(stage: str):
    start = time.perf_counter()
    try:
        yield
    finally:
        query_stage_duration_seconds.labels(stage=stage).observe(time.perf_counter() - start)
